export default [
    {
        name: "initial_migration",
        query: `
            CREATE TABLE migrations (
                id serial PRIMARY KEY,
                name text UNIQUE not null,
                migration_group int not null,
                migrated_at timestamp not null
            );`,
        rollback_query: `DROP TABLE migrations;`
    },
    {
        name: "create_accounts_table",
        query: `
            CREATE TABLE IF NOT EXISTS public.accounts
            (
                id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
                name character varying(300) COLLATE pg_catalog."default" NOT NULL DEFAULT 'Player'::character varying,
                device_id character varying(500) COLLATE pg_catalog."default" NOT NULL DEFAULT NULL::character varying,
                gems integer NOT NULL DEFAULT 0,
                is_online integer NOT NULL DEFAULT 0,
                client_id integer NOT NULL DEFAULT 0,
                trophies integer NOT NULL DEFAULT 0,
                banned integer NOT NULL DEFAULT 0,
                shield timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                xp integer NOT NULL DEFAULT 0,
                level integer NOT NULL DEFAULT 1,
                clan_join_timer timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                clan_id integer NOT NULL DEFAULT 0,
                clan_rank integer NOT NULL DEFAULT 0,
                war_id integer NOT NULL DEFAULT '-1'::integer,
                war_pos integer NOT NULL DEFAULT 0,
                global_chat_blocked integer NOT NULL DEFAULT 0,
                clan_chat_blocked integer NOT NULL DEFAULT 0,
                last_chat timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                chat_color character varying(50) COLLATE pg_catalog."default" NOT NULL DEFAULT ''::character varying,
                email character varying(1000) COLLATE pg_catalog."default" NOT NULL DEFAULT ''::character varying,
                password character varying(1000) COLLATE pg_catalog."default" NOT NULL DEFAULT ''::character varying,
                map_layout integer NOT NULL DEFAULT 0,
                shld_cldn_1 timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                shld_cldn_2 timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                shld_cldn_3 timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                last_login timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                CONSTRAINT accounts_pkey PRIMARY KEY (id)
            );`,
        rollback_query: `DROP TABLE accounts;`
    },
    {
        name: "create_battles_table",
        query: `
        CREATE TABLE IF NOT EXISTS public.battles
        (
            id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
            attacker_id integer NOT NULL,
            defender_id integer NOT NULL,
            replay_path character varying(2000) COLLATE pg_catalog."default" NOT NULL DEFAULT NULL::character varying,
            end_time timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
            stars integer NOT NULL DEFAULT 0,
            trophies integer NOT NULL DEFAULT 0,
            looted_gold integer NOT NULL DEFAULT 0,
            looted_elixir integer NOT NULL DEFAULT 0,
            looted_dark_elixir integer NOT NULL DEFAULT 0,
            seen integer NOT NULL DEFAULT 0,
            CONSTRAINT battles_pkey PRIMARY KEY (id)
        );`,
        rollback_query: `DROP TABLE battles;`
    },
    {
        name: "create_buildings_table",
        query: `
        CREATE TABLE IF NOT EXISTS public.buildings
        (
            id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
            global_id character varying(50) COLLATE pg_catalog."default" NOT NULL DEFAULT ''::character varying,
            account_id integer NOT NULL,
            level integer NOT NULL DEFAULT 0,
            x_position integer NOT NULL DEFAULT 0,
            y_position integer NOT NULL DEFAULT 0,
            gold_storage real NOT NULL DEFAULT 0,
            elixir_storage real NOT NULL DEFAULT 0,
            dark_elixir_storage real NOT NULL DEFAULT 0,
            boost timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
            construction_time timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
            is_constructing integer NOT NULL DEFAULT 0,
            construction_build_time integer NOT NULL DEFAULT 0,
            track_time timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
            x_war integer NOT NULL DEFAULT '-1'::integer,
            y_war integer NOT NULL DEFAULT '-1'::integer,
            CONSTRAINT buildings_pkey PRIMARY KEY (id)
        );`,
        rollback_query: `DROP TABLE buildings;`
    },
    {
        name: "create_chat_messages_table",
        query: `
        CREATE TABLE IF NOT EXISTS public.chat_messages
        (
            id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
            account_id integer NOT NULL DEFAULT 0,
            type integer NOT NULL DEFAULT 0,
            global_id integer NOT NULL DEFAULT 0,
            clan_id integer NOT NULL DEFAULT 0,
            message character varying(1000) COLLATE pg_catalog."default" NOT NULL DEFAULT NULL::character varying,
            send_time timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
            CONSTRAINT chat_messages_pkey PRIMARY KEY (id)
        )
        ;`,
        rollback_query: `DROP TABLE chat_messages;`
    },
    {
        name: "create_chat_reports_table",
        query: `
        CREATE TABLE IF NOT EXISTS public.chat_reports
        (
            id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
            message_id integer NOT NULL,
            reporter_id integer NOT NULL,
            target_id integer NOT NULL,
            message character varying(500) COLLATE pg_catalog."default" NOT NULL DEFAULT NULL::character varying,
            report_time timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
            CONSTRAINT chat_reports_pkey PRIMARY KEY (id)
        );`,
        rollback_query: `DROP TABLE chat_reports;`
    },
    {
        name: "create_clan_join_requests_table",
        query: `
        CREATE TABLE IF NOT EXISTS public.clan_join_requests
        (
            id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
            clan_id integer NOT NULL,
            account_id integer NOT NULL,
            request_time timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
            CONSTRAINT clan_join_requests_pkey PRIMARY KEY (id)
        );`,
        rollback_query: `DROP TABLE clan_join_requests;`
    },
    {
        name: "create_clan_war_attacks_table",
        query: `
        CREATE TABLE IF NOT EXISTS public.clan_war_attacks
        (
            id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
            war_id integer NOT NULL,
            attacker_id integer NOT NULL,
            defender_id integer NOT NULL,
            start_time timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
            stars integer NOT NULL DEFAULT 0,
            looted_gold integer NOT NULL DEFAULT 0,
            looted_elixir integer NOT NULL DEFAULT 0,
            looted_dark_elixir integer NOT NULL DEFAULT 0,
            replay_path character varying(2000) COLLATE pg_catalog."default" NOT NULL DEFAULT ''::character varying,
            CONSTRAINT clan_war_attacks_pkey PRIMARY KEY (id)
        );`,
        rollback_query: `DROP TABLE clan_war_attacks;`
    },
    {
        name: "create_clan_wars_table",
        query: `
        CREATE TABLE IF NOT EXISTS public.clan_wars
        (
            id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
            clan_1_id integer NOT NULL,
            clan_2_id integer NOT NULL,
            start_time timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
            stage integer NOT NULL DEFAULT 1,
            report_path character varying(2000) COLLATE pg_catalog."default" NOT NULL DEFAULT ''::character varying,
            winner_id integer NOT NULL DEFAULT 0,
            clan_1_stars integer NOT NULL DEFAULT 0,
            clan_2_stars integer NOT NULL DEFAULT 0,
            war_size integer NOT NULL DEFAULT 0,
            CONSTRAINT clan_wars_pkey PRIMARY KEY (id)
        );`,
        rollback_query: `DROP TABLE clan_wars;`
    },
    {
        name: "create_clan_wars_search_table",
        query: `
        CREATE TABLE IF NOT EXISTS public.clan_wars_search
        (
            id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
            clan_id integer NOT NULL,
            account_id integer NOT NULL,
            search_time timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
            CONSTRAINT clan_wars_search_pkey PRIMARY KEY (id)
        );`,
        rollback_query: `DROP TABLE clan_wars_search;`
    },
    {
        name: "create_clans_table",
        query: `
        CREATE TABLE IF NOT EXISTS public.clans
        (
            id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
            name character varying(300) COLLATE pg_catalog."default" NOT NULL DEFAULT NULL::character varying,
            join_type integer NOT NULL DEFAULT 0,
            xp integer NOT NULL DEFAULT 0,
            level integer NOT NULL DEFAULT 1,
            trophies integer NOT NULL DEFAULT 0,
            min_trophies integer NOT NULL DEFAULT 0,
            min_townhall_level integer NOT NULL DEFAULT 1,
            pattern integer NOT NULL DEFAULT 0,
            background integer NOT NULL DEFAULT 0,
            pattern_color character varying(50) COLLATE pg_catalog."default" NOT NULL DEFAULT NULL::character varying,
            background_color character varying(50) COLLATE pg_catalog."default" NOT NULL DEFAULT NULL::character varying,
            war_id integer NOT NULL DEFAULT 0,
            CONSTRAINT clans_pkey PRIMARY KEY (id)
        );`,
        rollback_query: `DROP TABLE clans;`
    },
    {
        name: "create_iap_table",
        query: `
        CREATE TABLE IF NOT EXISTS public.iap
        (
            id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
            account_id integer NOT NULL,
            market character varying(100) COLLATE pg_catalog."default" NOT NULL DEFAULT NULL::character varying,
            product_id character varying(100) COLLATE pg_catalog."default" NOT NULL DEFAULT NULL::character varying,
            token character varying(100) COLLATE pg_catalog."default" NOT NULL DEFAULT NULL::character varying,
            save_time timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
            price character varying(100) COLLATE pg_catalog."default" NOT NULL DEFAULT '0'::character varying,
            currency character varying(50) COLLATE pg_catalog."default" NOT NULL DEFAULT 'USD'::character varying,
            validated integer NOT NULL DEFAULT 0,
            CONSTRAINT iap_pkey PRIMARY KEY (id)
        );`,
        rollback_query: `DROP TABLE iap;`
    },
    {
        name: "create_research_table",
        query: `
        CREATE TABLE IF NOT EXISTS public.research
        (
            id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
            type integer NOT NULL,
            account_id integer NOT NULL,
            global_id character varying(100) COLLATE pg_catalog."default" NOT NULL DEFAULT NULL::character varying,
            level integer NOT NULL DEFAULT 1,
            researching timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
            CONSTRAINT research_pkey PRIMARY KEY (id)
        );`,
        rollback_query: `DROP TABLE research;`
    },
    {
        name: "create_server_buildings_table",
        query: `
        CREATE TABLE IF NOT EXISTS public.server_buildings
        (
            id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
            global_id character varying(50) COLLATE pg_catalog."default" NOT NULL DEFAULT ''::character varying,
            level integer NOT NULL DEFAULT 0,
            req_gold integer NOT NULL DEFAULT 0,
            req_elixir integer NOT NULL DEFAULT 0,
            req_gems integer NOT NULL DEFAULT 0,
            req_dark_elixir integer NOT NULL DEFAULT 0,
            columns_count integer NOT NULL DEFAULT 0,
            rows_count integer NOT NULL DEFAULT 0,
            capacity integer NOT NULL DEFAULT 0,
            gold_capacity integer NOT NULL DEFAULT 0,
            elixir_capacity integer NOT NULL DEFAULT 0,
            dark_elixir_capacity integer NOT NULL DEFAULT 0,
            speed real NOT NULL DEFAULT 0,
            health integer NOT NULL DEFAULT 100,
            damage real NOT NULL DEFAULT 0,
            target_type character varying(50) COLLATE pg_catalog."default" NOT NULL DEFAULT 'none'::character varying,
            radius real NOT NULL DEFAULT 0,
            blind_radius real NOT NULL DEFAULT 0,
            splash_radius real NOT NULL DEFAULT 0,
            projectile_speed real NOT NULL DEFAULT 0,
            build_time integer NOT NULL DEFAULT 0,
            gained_xp integer NOT NULL DEFAULT 0,
            CONSTRAINT server_buildings_pkey PRIMARY KEY (id)
        );`,
        rollback_query: `DROP TABLE server_buildings;`
    },
    {
        name: "create_server_quest_battles",
        query: `
        CREATE TABLE IF NOT EXISTS public.server_quest_battles
        (
            id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
            category integer NOT NULL DEFAULT 0,
            order_index integer NOT NULL,
            class_dara text COLLATE pg_catalog."default" NOT NULL,
            CONSTRAINT server_quest_battles_pkey PRIMARY KEY (id)
        );`,
        rollback_query: `DROP TABLE server_quest_battles;`
    },
    {
        name: "create_server_spells_table",
        query: `
        CREATE TABLE IF NOT EXISTS public.server_spells
        (
            id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
            global_id character varying(50) COLLATE pg_catalog."default" NOT NULL DEFAULT ''::character varying,
            level integer NOT NULL DEFAULT 1,
            building_code integer NOT NULL DEFAULT 0,
            req_gold integer NOT NULL DEFAULT 0,
            req_elixir integer NOT NULL DEFAULT 0,
            req_gem integer NOT NULL DEFAULT 0,
            req_dark_elixir integer NOT NULL DEFAULT 0,
            brew_time integer NOT NULL DEFAULT 0,
            housing integer NOT NULL DEFAULT 1,
            radius real NOT NULL DEFAULT 1,
            pulses_count integer NOT NULL DEFAULT 0,
            pulses_duration real NOT NULL DEFAULT 0,
            pulses_value real NOT NULL DEFAULT 0,
            pulses_value_2 real NOT NULL DEFAULT 0,
            research_time integer NOT NULL DEFAULT 0,
            research_gold integer NOT NULL DEFAULT 0,
            research_elixir integer NOT NULL DEFAULT 0,
            research_dark_elixir integer NOT NULL DEFAULT 0,
            research_gems integer NOT NULL DEFAULT 0,
            research_xp integer NOT NULL DEFAULT 0,
            CONSTRAINT server_spells_pkey PRIMARY KEY (id)
        );`,
        rollback_query: `DROP TABLE server_spells;`
    },
    {
        name: "create_server_units_table",
        query: `
        CREATE TABLE IF NOT EXISTS public.server_units
        (
            id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
            global_id character varying(50) COLLATE pg_catalog."default" NOT NULL DEFAULT ''::character varying,
            level integer NOT NULL DEFAULT 1,
            building_code integer NOT NULL DEFAULT 0,
            req_gold integer NOT NULL DEFAULT 0,
            req_elixir integer NOT NULL DEFAULT 0,
            req_gem integer NOT NULL DEFAULT 0,
            req_dark_elixir integer NOT NULL DEFAULT 0,
            train_time integer NOT NULL DEFAULT 0,
            health integer NOT NULL DEFAULT 10,
            housing integer NOT NULL DEFAULT 1,
            damage real NOT NULL DEFAULT 1,
            attack_range real NOT NULL DEFAULT 0,
            attack_speed real NOT NULL DEFAULT 1,
            splash_range real NOT NULL DEFAULT 0,
            projectile_speed real NOT NULL DEFAULT 0,
            move_speed real NOT NULL DEFAULT 1,
            move_type character varying(50) COLLATE pg_catalog."default" NOT NULL DEFAULT 'ground'::character varying,
            target_priority character varying(50) COLLATE pg_catalog."default" NOT NULL DEFAULT 'all'::character varying,
            priority_multiplier real NOT NULL DEFAULT 1,
            research_time integer NOT NULL DEFAULT 0,
            research_gold integer NOT NULL DEFAULT 0,
            research_elixir integer NOT NULL DEFAULT 0,
            research_dark_elixir integer NOT NULL DEFAULT 0,
            research_gems integer NOT NULL DEFAULT 0,
            research_xp integer NOT NULL DEFAULT 0,
            CONSTRAINT server_units_pkey PRIMARY KEY (id)
        );`,
        rollback_query: `DROP TABLE server_units;`
    },
    {
        name: "create_spells_table",
        query: `
        CREATE TABLE IF NOT EXISTS public.spells
        (
            id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
            global_id character varying(50) COLLATE pg_catalog."default" NOT NULL DEFAULT ''::character varying,
            level integer NOT NULL DEFAULT 1,
            account_id integer NOT NULL,
            brewed integer NOT NULL DEFAULT 0,
            ready integer NOT NULL DEFAULT 0,
            brewed_time real NOT NULL DEFAULT 0,
            CONSTRAINT spells_pkey PRIMARY KEY (id)
        );`,
        rollback_query: `DROP TABLE spells;`
    },
    {
        name: "create_units_table",
        query: `
        CREATE TABLE IF NOT EXISTS public.units
        (
            id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
            global_id character varying(50) COLLATE pg_catalog."default" NOT NULL DEFAULT ''::character varying,
            level integer NOT NULL DEFAULT 1,
            account_id integer NOT NULL,
            trained integer NOT NULL DEFAULT 0,
            ready integer NOT NULL DEFAULT 0,
            trained_time real NOT NULL DEFAULT 0,
            CONSTRAINT units_pkey PRIMARY KEY (id)
        );`,
        rollback_query: `DROP TABLE units;`
    },
    {
        name: "create_verification_codes_table",
        query: `
        CREATE TABLE IF NOT EXISTS public.verification_codes
        (
            id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
            target character varying(1000) COLLATE pg_catalog."default" NOT NULL DEFAULT NULL::character varying,
            device_id character varying(1000) COLLATE pg_catalog."default" NOT NULL DEFAULT NULL::character varying,
            code character varying(50) COLLATE pg_catalog."default" NOT NULL DEFAULT NULL::character varying,
            expire_time timestamp without time zone NOT NULL,
            CONSTRAINT verification_codes_pkey PRIMARY KEY (id)
        );`,
        rollback_query: `DROP TABLE verification_codes;`
    },
];